services:
  db:
    image: mysql
    container_name: mysql_db
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"
    networks:
      - mysqlprojectnetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    container_name: mysql_backend
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mysqlprojectnetwork
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mysql_frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    networks:
      - mysqlprojectnetwork
    depends_on:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mysql_phpmyadmin
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - mysqlprojectnetwork
    ports:
      - "8080:80"

volumes:
  mysql-data:

networks:
  mysqlprojectnetwork:
    driver: bridge